const URL_RE=/https?:\/\/[^\s"'<>\\)\]]+/gi;
let items=[];const states=new Map();
const E=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const scripts=c=>c?.data?.extensions?.regex_scripts;
function walk(v,p=[],o=[]){if(typeof v==='string')o.push({p,v});else if(Array.isArray(v))v.forEach((x,i)=>walk(x,[...p,i],o));else if(v&&typeof v==='object')Object.entries(v).forEach(([k,x])=>walk(x,[...p,k],o));return o}
function usage(p){return({replaceString:'\u66ff\u6362\u7ed3\u679c / \u663e\u793a\u5185\u5bb9',findRegex:'\u67e5\u627e\u89c4\u5219',trimStrings:'\u88c1\u526a\u6587\u672c',scriptName:'\u811a\u672c\u540d\u79f0'})[String(p.at(-1))]||`\u6b63\u5219\u5b57\u6bb5: ${p.at(-1)}`}
function scan(){items=[];const{characters=[]}=SillyTavern.getContext();characters.forEach((c,ci)=>{const ss=scripts(c);if(!Array.isArray(ss))return;ss.forEach((s,si)=>walk(s).forEach(({p,v})=>{for(const m of v.matchAll(URL_RE))items.push({id:`${ci}:${si}:${p.join('.')}:${m.index}`,ci,si,p,url:m[0],selected:true,card:c.name||c.data?.name||`\u89d2\u8272 ${ci+1}`,script:s.scriptName||s.name||`\u6b63\u5219 ${si+1}`,usage:usage(p)})}))});render()}
function grouped(){const m=new Map;items.forEach(x=>m.has(x.url)?m.get(x.url).push(x):m.set(x.url,[x]));const rank={broken:0,loading:1,unknown:2,ok:3};return[...m].map(([url,refs])=>({url,refs,state:states.get(url)||'unknown'})).sort((a,b)=>rank[a.state]-rank[b.state]||b.refs.length-a.refs.length)}
function status(s){return({ok:'\u53ef\u9884\u89c8',broken:'\u65e0\u6cd5\u52a0\u8f7d',loading:'\u68c0\u6d4b\u4e2d',unknown:'\u5f85\u68c0\u6d4b'})[s]}
function render(){const filter=document.querySelector('#sihm-filter')?.value||'all',gs=grouped(),shown=gs.filter(g=>filter==='all'||g.state===filter),list=document.querySelector('#sihm-results');document.querySelector('#sihm-count').textContent=`${gs.length} \u4e2a\u4e0d\u540c\u94fe\u63a5 / ${items.length} \u5904\u5f15\u7528 / ${gs.filter(g=>g.state==='broken').length} \u4e2a\u65e0\u6cd5\u52a0\u8f7d`;list.innerHTML=shown.length?shown.map(g=>`<article class="sihm-group" data-url="${E(g.url)}"><div class="sihm-summary"><img class="sihm-preview" src="${E(g.url)}" loading="lazy"><div class="sihm-group-info"><div><span class="sihm-status ${g.state}">${status(g.state)}</span> <strong>\u51fa\u73b0\u5728 ${new Set(g.refs.map(x=>x.ci)).size} \u5f20\u5361\uff0c\u5171 ${g.refs.length} \u5904</strong></div><a href="${E(g.url)}" target="_blank" rel="noreferrer">${E(g.url)}</a><div class="sihm-replace"><input class="text_pole sihm-new" placeholder="\u8f93\u5165\u65b0\u7684\u5b8c\u6574 URL"><button class="menu_button all">\u66ff\u6362\u6240\u6709\u76f8\u540c\u94fe\u63a5</button><button class="menu_button selected">\u4ec5\u66ff\u6362\u52fe\u9009\u4f4d\u7f6e</button></div></div><button class="menu_button toggle">\u5c55\u5f00\u4f4d\u7f6e</button></div><div class="sihm-locations" hidden>${g.refs.map(x=>`<label class="sihm-location" data-id="${E(x.id)}"><input type="checkbox" ${x.selected?'checked':''}><span><strong>${E(x.card)}</strong> / ${E(x.script)}<small>${E(x.usage)} / ${E(x.p.join('.'))}</small></span></label>`).join('')}</div></article>`).join(''):'<div class="sihm-empty">\u5f53\u524d\u7b5b\u9009\u4e0b\u6ca1\u6709\u94fe\u63a5\u3002</div>';bind()}
function bind(){document.querySelectorAll('.sihm-group').forEach(row=>{const url=row.dataset.url,img=row.querySelector('img');row.querySelector('.toggle').onclick=e=>{const b=row.querySelector('.sihm-locations');b.hidden=!b.hidden;e.target.textContent=b.hidden?'\u5c55\u5f00\u4f4d\u7f6e':'\u6536\u8d77\u4f4d\u7f6e'};row.querySelectorAll('.sihm-location').forEach(l=>l.querySelector('input').onchange=e=>items.find(x=>x.id===l.dataset.id).selected=e.target.checked);row.querySelector('.all').onclick=()=>replace(url,row.querySelector('.sihm-new').value.trim(),false);row.querySelector('.selected').onclick=()=>replace(url,row.querySelector('.sihm-new').value.trim(),true);img.onload=()=>mark(row,url,'ok');img.onerror=()=>mark(row,url,'broken');if(!states.has(url))states.set(url,'loading');if(img.complete)img.naturalWidth?img.onload():img.onerror()})}
function mark(row,url,state){states.set(url,state);const b=row.querySelector('.sihm-status');b.textContent=status(state);b.className=`sihm-status ${state}`;row.querySelector('img').classList.toggle('broken',state==='broken');const gs=grouped();document.querySelector('#sihm-count').textContent=`${gs.length} \u4e2a\u4e0d\u540c\u94fe\u63a5 / ${items.length} \u5904\u5f15\u7528 / ${gs.filter(g=>g.state==='broken').length} \u4e2a\u65e0\u6cd5\u52a0\u8f7d`}
function setAt(root,p,value){let c=root;for(let i=0;i<p.length-1;i++)c=c[p[i]];c[p.at(-1)]=value}
function backup(data){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=Object.assign(document.createElement('a'),{href:url,download:`sihm-backup-${new Date().toISOString().replace(/[:.]/g,'-')}.json`});a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function write(changes){if(!changes.length)return toastr.warning('\u6ca1\u6709\u9009\u4e2d\u53ef\u66ff\u6362\u7684\u4f4d\u7f6e\u3002');const ctx=SillyTavern.getContext(),affected=[...new Set(changes.map(x=>x.item.ci))];backup(affected.map(ci=>({character:ctx.characters[ci]?.name,avatar:ctx.characters[ci]?.avatar,regex_scripts:structuredClone(scripts(ctx.characters[ci]))})));for(const ci of affected){const ss=structuredClone(scripts(ctx.characters[ci]));for(const{item,replacement}of changes.filter(x=>x.item.ci===ci)){const s=ss[item.si],current=item.p.reduce((v,k)=>v[k],s);setAt(s,item.p,current.split(item.url).join(replacement))}await ctx.writeExtensionField(ci,'regex_scripts',ss)}toastr.success(`\u5df2\u66f4\u65b0 ${affected.length} \u5f20\u5361\u7684 ${changes.length} \u5904\u5f15\u7528\uff0c\u5e76\u4e0b\u8f7d\u5907\u4efd\u3002`);scan()}
function replace(oldUrl,newUrl,selected){if(!/^https?:\/\//i.test(newUrl))return toastr.warning('\u8bf7\u8f93\u5165\u6709\u6548\u7684\u65b0 URL\u3002');return write(items.filter(x=>x.url===oldUrl&&(!selected||x.selected)).map(item=>({item,replacement:newUrl})))}
function prefixes(){const old=document.querySelector('#sihm-old-prefix').value.trim(),next=document.querySelector('#sihm-new-prefix').value.trim();if(!old||!/^https?:\/\//i.test(next))return toastr.warning('\u8bf7\u586b\u5199\u6709\u6548\u7684\u65b0\u65e7\u524d\u7f00\u3002');return write(items.filter(x=>x.selected&&x.url.startsWith(old)).map(item=>({item,replacement:next+x.url.slice(old.length)})))}
function mount(){if(document.querySelector('#sihm-panel'))return;document.body.insertAdjacentHTML('beforeend',`<div id="sihm-panel" class="sihm-overlay" hidden><section class="sihm-dialog"><header><h3>\u89d2\u8272\u5361\u56fe\u5e8a\u7ba1\u5bb6</h3><button id="sihm-close" class="menu_button">\u5173\u95ed</button></header><p>\u5931\u6548\u94fe\u63a5\u4f18\u5148\u663e\u793a\uff1b\u76f8\u540c URL \u81ea\u52a8\u5f52\u7ec4\u3002\u5199\u5165\u524d\u81ea\u52a8\u4e0b\u8f7d\u5907\u4efd\u3002</p><div class="sihm-controls"><select id="sihm-filter" class="text_pole"><option value="all">\u5168\u90e8\u94fe\u63a5</option><option value="broken">\u53ea\u770b\u65e0\u6cd5\u52a0\u8f7d</option><option value="ok">\u53ea\u770b\u6b63\u5e38\u94fe\u63a5</option></select><input id="sihm-old-prefix" class="text_pole" placeholder="\u65e7\u56fe\u5e8a\u524d\u7f00"><span>\u2192</span><input id="sihm-new-prefix" class="text_pole" placeholder="\u65b0\u56fe\u5e8a\u524d\u7f00"><button id="sihm-prefix" class="menu_button">\u6279\u91cf\u8fc1\u79fb\u52fe\u9009\u4f4d\u7f6e</button></div><div id="sihm-count"></div><div id="sihm-results"></div></section></div>`);document.querySelector('#sihm-close').onclick=()=>document.querySelector('#sihm-panel').hidden=true;document.querySelector('#sihm-panel').onclick=e=>{if(e.target.id==='sihm-panel')e.target.hidden=true};document.querySelector('#sihm-filter').onchange=render;document.querySelector('#sihm-prefix').onclick=prefixes;const b=document.createElement('div');b.id='sihm-open';b.className='list-group-item flex-container flexGap5 interactable';b.tabIndex=0;b.innerHTML='<i class="fa-solid fa-images"></i><span>\u89d2\u8272\u5361\u56fe\u5e8a\u7ba1\u5bb6</span>';b.onclick=()=>{document.querySelector('#sihm-panel').hidden=false;scan()};(document.querySelector('#extensionsMenu')||document.body).append(b)}
$(mount);

