const URL_RE=/https?:\/\/[^\s"'<>\\)\]]+/gi;
const MEDIA_REF_RE=/(?:\/\/[^\s"'<>\\)\]]+|(?:\.{0,2}\/)?(?:[\p{L}\p{N}_@%+~.-]+\/)*[\p{L}\p{N}_@%+~.-]+\.(?:png|jpe?g|gif|webp|avif|bmp|svg|mp3)(?:[?#][^\s"'<>\\)\]]*)?)/giu;
let items=[],scanRunning=false,scannedMode='';const states=new Map(),worldBooks=new Map();
const E=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const scripts=c=>c?.data?.extensions?.regex_scripts;
const PHONE_RE=/\u5c0f\u624b\u673a|\u5c0f\u722a\u673a|\u8f7b\u91cf\u624b\u673a|\u540c\u5c42\u624b\u673a|\u624b\u673a\u6d88\u606f|\u670b\u53cb\u5708|\u804a\u5929\u6846|user\u6d88\u606f|\u5bf9\u65b9\u6d88\u606f|\u4e2a\u4eba\u4e3b\u9875|\u8868\u60c5\u5305|\u65e5\u8bb0|\u5b9a\u4f4d|\u8f6c\u8d26|\u8bed\u97f3(?:\u6d88\u606f|\u901a\u8bdd)|\u7eaf\u8272\u56fe\u7247|\u76f4\u64ad\u95f4|\u52a8\u6001/i;
function isFontRef(url){try{const u=new URL(url,location.href);return /(^|\.)fonts\.(googleapis|gstatic)\.com$/i.test(u.hostname)||/\.(?:woff2?|ttf|otf|eot)(?:$|[?#])/i.test(u.pathname)}catch{return /fonts\.|\.(?:woff2?|ttf|otf|eot)(?:$|[?#])/i.test(String(url))}}
function sectionOf(x){if(['beauty','preset'].includes(x.source))return'beauty';if(PHONE_RE.test(x.context||''))return'phone';if(['lore','world'].includes(x.source))return'world';return'character'}
function mediaType(url,text=''){let p;try{p=new URL(url,location.href).pathname.toLowerCase()}catch{return null}if(/\.(css|js|mjs|html?|php)$/.test(p))return null;if(/\.(png|jpe?g|gif|webp|avif|bmp|svg)$/.test(p))return'image';if(/\.mp3$/.test(p))return'mp3';const t=String(text).toLowerCase();if(t.includes('<img')||t.includes('![')||t.includes('background-image'))return'image';if(t.includes('<audio')||t.includes('audio/'))return'mp3';return null}
function mediaRefs(text){const found=[],covered=[];for(const re of [URL_RE,MEDIA_REF_RE]){re.lastIndex=0;for(const m of text.matchAll(re)){const start=m.index,end=start+m[0].length;if(covered.some(([a,b])=>start>=a&&end<=b))continue;const media=mediaType(m[0],text);if(!media)continue;covered.push([start,end]);found.push({raw:m[0],index:start,media})}}return found.sort((a,b)=>a.index-b.index)}
function describeRef(text,m,p=[],label=''){const start=m.index,end=start+m.raw.length,before=text.slice(Math.max(0,start-140),start),after=text.slice(end,Math.min(text.length,end+140)),near=(before+' '+after).replace(/\s+/g,' ').trim();let subject='',style='',kind=m.media==='mp3'?'\u97f3\u9891':'\u5185\u5bb9\u56fe\u7247';const tagStart=text.lastIndexOf('<img',start),tagEnd=text.indexOf('>',end);if(tagStart>=0&&start-tagStart<500&&tagEnd>=end&&tagEnd-end<500){const tag=text.slice(tagStart,tagEnd+1);subject=tag.match(/alt=["']([^"']+)["']/i)?.[1]||'';style=tag.match(/class=["']([^"']+)["']/i)?.[1]||'';kind=/avatar|\u5934\u50cf/i.test(tag)?'\u5934\u50cf':'HTML \u56fe\u7247'}if(!subject)subject=before.match(/(?:\[|\u3010)([^\]\u3011\n]{1,24})(?:\]|\u3011)[^\n]{0,100}$/)?.[1]||before.match(/([\p{L}\p{N}_-]{1,20})(?:\u7684)?\u5934\u50cf\s*[=:：]?\s*$/u)?.[1]||'';if(/background(?:-image)?\s*:/i.test(near))kind='\u80cc\u666f\u56fe';else if(/cover|banner|\u5c01\u9762|\u6a2a\u5e45/i.test(near))kind='\u5c01\u9762 / \u6a2a\u5e45';else if(/avatar|\u5934\u50cf/i.test(near))kind='\u5934\u50cf';else if(/emoji|\u8868\u60c5/i.test(near))kind='\u8868\u60c5\u56fe';const field=String(p.at(-1)||label||'\u672a\u77e5\u5b57\u6bb5'),snippet=(before.slice(-70)+m.raw+after.slice(0,70)).replace(/\s+/g,' ').trim();return{subject,kind,style,field,snippet}}
function baseName(ref){try{return decodeURIComponent(new URL(ref,location.href).pathname.split('/').pop()||'').toLowerCase()}catch{return String(ref).split(/[/?#]/).pop().toLowerCase()}}
function absoluteRef(ref){try{return ref.startsWith('//')?`${location.protocol}${ref}`:new URL(ref,location.href).href}catch{return ref}}
function finalizeRefs(){const byName=new Map;for(const x of items){if(!/^https?:\/\//i.test(x.url))continue;const name=baseName(x.url);if(!byName.has(name))byName.set(name,new Set);byName.get(name).add(x.url)}for(const x of items){x.match=x.url;x.partial=!/^https?:\/\//i.test(x.url);if(!x.partial)continue;const matches=byName.get(baseName(x.url));x.url=matches?.size===1?[...matches][0]:absoluteRef(x.url);x.usage+=matches?.size===1?' / \u5df2\u6309\u6587\u4ef6\u540d\u5173\u8054\u5b8c\u6574\u94fe\u63a5':' / \u90e8\u5206\u94fe\u63a5'} }
function walk(v,p=[],o=[]){if(typeof v==='string')o.push({p,v});else if(Array.isArray(v))v.forEach((x,i)=>walk(x,[...p,i],o));else if(v&&typeof v==='object')Object.entries(v).forEach(([k,x])=>walk(x,[...p,k],o));return o}
function usage(p){return({replaceString:'\u66ff\u6362\u7ed3\u679c / \u663e\u793a\u5185\u5bb9',findRegex:'\u67e5\u627e\u89c4\u5219',trimStrings:'\u88c1\u526a\u6587\u672c',scriptName:'\u811a\u672c\u540d\u79f0'})[String(p.at(-1))]||`\u6b63\u5219\u5b57\u6bb5: ${p.at(-1)}`}
function addScripts(ss,source,owner=''){if(!Array.isArray(ss))return;ss.forEach((s,si)=>walk(s).forEach(({p,v})=>{for(const m of mediaRefs(v)){items.push({id:`${source}:${owner}:${si}:${p.join('.')}:${m.index}`,source,owner,si,p,url:m.raw,media:m.media,selected:true,card:owner,script:s.scriptName||s.name||`\u6b63\u5219 ${si+1}`,usage:usage(p),context:[s.scriptName,s.name,p.join('.'),v].join(' '),detail:describeRef(v,m,p,s.scriptName||s.name)})}}))}
function addReadOnly(value,source,owner,label,base=[]){walk(value).forEach(({p,v})=>{for(const m of mediaRefs(v)){const ei=p.indexOf('entries'),entry=ei<0?null:p[ei+1],entryName=entry==null?'':value?.entries?.[entry]?.comment||entry;items.push({id:`${source}:${owner}:${[...base,...p].join('.')}:${m.index}`,source,owner,p:[...base,...p],url:m.raw,media:m.media,selected:false,readonly:true,card:owner,script:entryName||label,usage:'\u53ea\u8bfb\u5b9a\u4f4d / \u8bf7\u5728\u89d2\u8272\u7f16\u8f91\u5668\u4fee\u6539',context:[label,entryName,p.join('.'),v].join(' '),detail:describeRef(v,m,[...base,...p],entryName||label)})}})}
function addWorldBook(value,name){walk(value).forEach(({p,v})=>{for(const m of mediaRefs(v)){const ei=p.indexOf('entries'),entry=ei<0?null:p[ei+1],entryName=entry==null?'':value?.entries?.[entry]?.comment||entry;items.push({id:`world:${name}:${p.join('.')}:${m.index}`,source:'world',owner:name,p,url:m.raw,media:m.media,selected:true,card:name,script:entry==null?'\u4e16\u754c\u4e66':entryName,usage:`\u5916\u7f6e\u4e16\u754c\u4e66 / ${p.join('.')}`,context:[name,entryName,p.join('.'),v].join(' '),detail:describeRef(v,m,p,entryName||name)})}})}
async function runPool(values,limit,fn){let next=0;await Promise.all(Array.from({length:Math.min(limit,values.length)},async()=>{while(next<values.length){const i=next++;await fn(values[i],i)}}))}
function detectOne(url,media,timeout=6000){if(states.has(url)&&!['unknown','loading'].includes(states.get(url)))return Promise.resolve();states.set(url,'loading');return new Promise(resolve=>{const el=media==='mp3'?new Audio():new Image(),done=state=>{clearTimeout(timer);el.onload=el.onerror=el.oncanplay=null;states.set(url,state);resolve()},timer=setTimeout(()=>done('broken'),timeout);if(media==='mp3'){el.preload='metadata';el.oncanplay=()=>done('ok');el.onerror=()=>done('broken')}else{el.onload=()=>done('ok');el.onerror=()=>done('broken')}el.src=url})}
async function detectAll(count){const unique=[...new Map(items.filter(x=>!(isFontRef(x.url)&&sectionOf(x)!=='beauty')).map(x=>[x.url,x])).values()],pending=unique.filter(x=>!states.has(x.url)||['unknown','loading'].includes(states.get(x.url)));let done=0;await runPool(pending,8,async x=>{await detectOne(x.url,x.media);done++;if(count)count.textContent=`\u6b63\u5728\u68c0\u6d4b\u5a92\u4f53 ${done} / ${pending.length}\u2026`})}
async function scanWorldBooks(ctx,count){worldBooks.clear();const names=ctx.getWorldInfoNames?.()||[];if(!ctx.loadWorldInfo)return;let done=0;await runPool(names,4,async name=>{try{const data=await ctx.loadWorldInfo(name);if(data){worldBooks.set(name,data);addWorldBook(data,name)}}catch(e){console.warn('[SIHM] World info load skipped',name,e)}finally{done++;if(count)count.textContent=`\u6b63\u5728\u8bfb\u53d6\u4e16\u754c\u4e66 ${done} / ${names.length}\u2026`}})}
async function scan(){if(scanRunning)return;scanRunning=true;const mode=document.querySelector('#sihm-source')?.value||'character';try{items=[];const ctx=SillyTavern.getContext(),{characters=[]}=ctx,fields=['description','personality','scenario','first_mes','mes_example','creator_notes','system_prompt','post_history_instructions','alternate_greetings'],count=document.querySelector('#sihm-count'),indices=[...characters.keys()];if(mode!=='beauty'){let loaded=0;await runPool(indices,4,async ci=>{try{await ctx.unshallowCharacter?.(ci)}catch(e){console.warn('[SIHM] Character load skipped',ci,e)}finally{loaded++;if(count)count.textContent=`\u6b63\u5728\u8bfb\u53d6\u89d2\u8272\u5361 ${loaded} / ${characters.length}\u2026`}});for(const ci of indices){const c=characters[ci],d=c?.data||c,owner=String(ci);if(!c)continue;if(['character','phone'].includes(mode))addScripts(scripts(c),'card',owner);if(mode==='character'){fields.forEach(k=>addReadOnly(d?.[k],'cardtext',owner,k,[k]));addReadOnly(d?.assets,'assets',owner,'\u89d2\u8272\u8d44\u6e90',['assets']);if(c.avatar){let url;try{url=ctx.getThumbnailUrl?.('avatar',c.avatar)||`/characters/${encodeURIComponent(c.avatar)}`}catch{url=`/characters/${encodeURIComponent(c.avatar)}`}items.push({id:`avatar:${owner}`,source:'avatar',owner,url,media:'image',selected:false,readonly:true,card:owner,script:'\u89d2\u8272\u5934\u50cf',usage:'\u5934\u50cf\u5931\u6548\u65f6\u9700\u91cd\u65b0\u4e0a\u4f20',context:'\u5934\u50cf',detail:{subject:c.name||d?.name||'',kind:'\u89d2\u8272\u5934\u50cf',style:'',field:'avatar',snippet:c.avatar}})}}if(['world','phone'].includes(mode))addReadOnly(d?.character_book,'lore',owner,'\u5185\u5d4c\u4e16\u754c\u4e66',['character_book'])}if(['world','phone'].includes(mode))await scanWorldBooks(ctx,count)}if(mode==='beauty'){addScripts(ctx.extensionSettings?.regex,'beauty','\u5168\u5c40\u7f8e\u5316');try{addScripts(ctx.getPresetManager?.()?.readPresetExtensionField({path:'regex_scripts'}),'preset','\u5f53\u524d\u9884\u8bbe')}catch(e){console.warn('[SIHM] Preset scan skipped',e)}}items.forEach(x=>{if(['card','cardtext','lore','assets','avatar'].includes(x.source)){const c=characters[Number(x.owner)];x.card=c?.name||c?.data?.name||`\u89d2\u8272 ${Number(x.owner)+1}`}});finalizeRefs();items=items.filter(x=>sectionOf(x)===mode);await detectAll(count);scannedMode=mode;render()}finally{scanRunning=false;if((document.querySelector('#sihm-source')?.value||'character')!==mode)scan()}}
function grouped(){const m=new Map,counts=new Map,source=document.querySelector('#sihm-source')?.value||'character';for(const x of items){const section=sectionOf(x);if(isFontRef(x.url)&&section!=='beauty')continue;counts.set(x.url,(counts.get(x.url)||0)+1);if(section!==source)continue;m.has(x.url)?m.get(x.url).push(x):m.set(x.url,[x])}const rank={broken:0,loading:1,unknown:2,ok:3};return[...m].map(([url,refs])=>({url,refs,count:counts.get(url)||refs.length,state:states.get(url)||'unknown'})).sort((a,b)=>rank[a.state]-rank[b.state]||b.count-a.count)}
function status(s){return({ok:'\u53ef\u9884\u89c8',broken:'\u65e0\u6cd5\u52a0\u8f7d',loading:'\u68c0\u6d4b\u4e2d',unknown:'\u5f85\u68c0\u6d4b'})[s]}
function ignored(g){return g.state==='broken'&&g.count>20}
function groupVisible(g,view=document.querySelector('#sihm-filter')?.value||'issues'){return view==='ignored'?ignored(g):g.state!=='ok'&&!ignored(g)}
function updateCount(gs=grouped()){const issues=gs.filter(g=>g.state==='broken'&&!ignored(g)).length,hidden=gs.filter(ignored).length,checking=gs.filter(g=>g.state==='loading'||g.state==='unknown').length;document.querySelector('#sihm-count').textContent=`${issues} \u4e2a\u95ee\u9898 / ${hidden} \u4e2a\u5df2\u5ffd\u89c6${checking?` / ${checking} \u4e2a\u68c0\u6d4b\u4e2d`:''}`}
function detailHtml(x,labels){const d=x.detail||{},what=[d.subject,d.kind,d.style?`\u6837\u5f0f ${d.style}`:''].filter(Boolean).join(' \u00b7 '),where=[x.script,d.field,x.p?.length?x.p.join('.'):''].filter(Boolean).join(' / ');return`<span><strong>${labels[x.source]} / ${E(x.card)}</strong>${what?`<div>\u5b9a\u4f4d\uff1a${E(what)}</div>`:''}<small>\u4f4d\u7f6e\uff1a${E(where)}</small>${d.snippet?`<small class="sihm-snippet">\u9644\u8fd1\u5185\u5bb9\uff1a${E(d.snippet)}</small>`:''}</span>`}
function render(){const filter=document.querySelector('#sihm-filter')?.value||'all',gs=grouped(),shown=gs.filter(g=>groupVisible(g,filter)),list=document.querySelector('#sihm-results'),labels={card:'\u89d2\u8272\u5361\u6b63\u5219',cardtext:'\u89d2\u5361\u6587\u672c',lore:'\u5185\u5d4c\u4e16\u754c\u4e66',world:'\u5916\u7f6e\u4e16\u754c\u4e66',assets:'\u89d2\u8272\u8d44\u6e90',avatar:'\u89d2\u8272\u5934\u50cf',beauty:'\u7f8e\u5316',preset:'\u9884\u8bbe'};updateCount(gs);list.innerHTML=shown.length?shown.map(g=>{const ro=g.refs.every(x=>x.readonly);return`<article class="sihm-group" data-url="${E(g.url)}" data-count="${g.count}"><div class="sihm-summary">${g.refs[0].media==='mp3'?`<audio class="sihm-audio" src="${E(g.url)}" controls preload="metadata"></audio>`:`<img class="sihm-preview" src="${E(g.url)}" loading="lazy">`}<div class="sihm-group-info"><div><span class="sihm-status ${g.state}">${status(g.state)}</span> <strong>${g.refs[0].media==='mp3'?'MP3':'\u56fe\u7247'} / ${g.refs.length} \u5904 ${ro?' / \u53ea\u8bfb\u5b9a\u4f4d':''}</strong></div><a href="${E(g.url)}" target="_blank" rel="noreferrer">${E(g.url)}</a>${ro?'':`<div class="sihm-replace"><input class="text_pole sihm-new" placeholder="\u8f93\u5165\u65b0\u7684\u5b8c\u6574 URL"><button class="menu_button all">\u66ff\u6362\u6240\u6709\u76f8\u540c\u94fe\u63a5</button><button class="menu_button selected">\u4ec5\u66ff\u6362\u52fe\u9009\u4f4d\u7f6e</button></div>`}</div><button class="menu_button toggle">\u67e5\u770b\u5177\u4f53\u4f4d\u7f6e</button></div><div class="sihm-locations" hidden>${g.refs.map(x=>`<label class="sihm-location" data-id="${E(x.id)}"><input type="checkbox" ${x.selected?'checked':''} ${x.readonly?'disabled':''}>${detailHtml(x,labels)}</label>`).join('')}</div></article>`}).join(''):'<div class="sihm-empty">\u5f53\u524d\u7b5b\u9009\u4e0b\u6ca1\u6709\u5a92\u4f53\u94fe\u63a5\u3002</div>';bind()}
function bind(){document.querySelectorAll('.sihm-group').forEach(row=>{const url=row.dataset.url,media=row.querySelector('img,audio');if(!states.has(url))states.set(url,'loading');row.querySelector('.toggle').onclick=e=>{const b=row.querySelector('.sihm-locations');b.hidden=!b.hidden;e.target.textContent=b.hidden?'\u67e5\u770b\u5177\u4f53\u4f4d\u7f6e':'\u6536\u8d77\u4f4d\u7f6e'};row.querySelectorAll('.sihm-location').forEach(l=>l.querySelector('input').onchange=e=>items.find(x=>x.id===l.dataset.id).selected=e.target.checked);const all=row.querySelector('.all'),selected=row.querySelector('.selected'),input=row.querySelector('.sihm-new');if(all)all.onclick=()=>replace(url,input.value.trim(),false);if(selected)selected.onclick=()=>replace(url,input.value.trim(),true);if(media.tagName==='AUDIO'){media.oncanplay=()=>mark(row,url,'ok');media.onerror=()=>mark(row,url,'broken');if(media.readyState>=2)media.oncanplay()}else{media.onload=()=>mark(row,url,'ok');media.onerror=()=>mark(row,url,'broken');if(media.complete)media.naturalWidth?media.onload():media.onerror()}})}
function mark(row,url,state){states.set(url,state);const b=row.querySelector('.sihm-status');b.textContent=status(state);b.className=`sihm-status ${state}`;row.querySelector('img')?.classList.toggle('broken',state==='broken');const gs=grouped(),current=gs.find(g=>g.url===url);row.hidden=!current||!groupVisible(current);updateCount(gs)}
function setAt(root,p,value){let c=root;for(let i=0;i<p.length-1;i++)c=c[p[i]];c[p.at(-1)]=value}
function backup(data){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=Object.assign(document.createElement('a'),{href:url,download:`sihm-backup-${new Date().toISOString().replace(/[:.]/g,'-')}.json`});a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function applyTo(ss,changes){for(const{item,replacement}of changes){const s=ss[item.si],current=item.p.reduce((v,k)=>v[k],s);setAt(s,item.p,current.split(item.match||item.url).join(replacement))}return ss}
function applyAtRoot(root,changes){for(const{item,replacement}of changes){const current=item.p.reduce((v,k)=>v[k],root);setAt(root,item.p,current.split(item.match||item.url).join(replacement))}return root}
async function write(changes){if(!changes.length)return toastr.warning('\u6ca1\u6709\u9009\u4e2d\u53ef\u66ff\u6362\u7684\u4f4d\u7f6e\u3002');const ctx=SillyTavern.getContext(),cardIds=[...new Set(changes.filter(x=>x.item.source==='card').map(x=>Number(x.item.owner)))],beauty=changes.filter(x=>x.item.source==='beauty'),preset=changes.filter(x=>x.item.source==='preset'),world=changes.filter(x=>x.item.source==='world'),pm=ctx.getPresetManager?.();backup({cards:cardIds.map(ci=>({character:ctx.characters[ci]?.name,regex_scripts:structuredClone(scripts(ctx.characters[ci]))})),beauty_regex:beauty.length?structuredClone(ctx.extensionSettings?.regex):undefined,preset_regex:preset.length?structuredClone(pm?.readPresetExtensionField({path:'regex_scripts'})):undefined,world_info:Object.fromEntries([...new Set(world.map(x=>x.item.owner))].map(name=>[name,structuredClone(worldBooks.get(name))]))});for(const ci of cardIds){const cs=changes.filter(x=>x.item.source==='card'&&Number(x.item.owner)===ci);await ctx.writeExtensionField(ci,'regex_scripts',applyTo(structuredClone(scripts(ctx.characters[ci])),cs))}if(beauty.length){ctx.extensionSettings.regex=applyTo(structuredClone(ctx.extensionSettings.regex),beauty);ctx.saveSettingsDebounced()}if(preset.length&&pm){await pm.writePresetExtensionField({path:'regex_scripts',value:applyTo(structuredClone(pm.readPresetExtensionField({path:'regex_scripts'})),preset)})}for(const name of new Set(world.map(x=>x.item.owner))){const cs=world.filter(x=>x.item.owner===name),data=applyAtRoot(structuredClone(worldBooks.get(name)),cs);await ctx.saveWorldInfo(name,data,true);worldBooks.set(name,data)}toastr.success(`\u5df2\u66f4\u65b0 ${changes.length} \u5904\u5a92\u4f53\u5f15\u7528\uff0c\u5e76\u4e0b\u8f7d\u5907\u4efd\u3002`);scan()}
function visibleIds(){return new Set(grouped().filter(g=>groupVisible(g)).flatMap(g=>g.refs.map(x=>x.id)))}
function replace(oldUrl,newUrl,selected){if(!/^https?:\/\//i.test(newUrl))return toastr.warning('\u8bf7\u8f93\u5165\u6709\u6548\u7684\u65b0 URL\u3002');const visible=visibleIds();return write(items.filter(x=>!x.readonly&&visible.has(x.id)&&x.url===oldUrl&&(!selected||x.selected)).map(item=>({item,replacement:newUrl})))}
function prefixes(){const old=document.querySelector('#sihm-old-prefix').value.trim(),next=document.querySelector('#sihm-new-prefix').value.trim(),visible=visibleIds();if(!old||!/^https?:\/\//i.test(next))return toastr.warning('\u8bf7\u586b\u5199\u6709\u6548\u7684\u65b0\u65e7\u524d\u7f00\u3002');return write(items.filter(x=>!x.readonly&&visible.has(x.id)&&x.selected&&x.url.startsWith(old)).map(item=>({item,replacement:next+x.url.slice(old.length)})))}
function mount(){if(document.querySelector('#sihm-panel'))return;document.body.insertAdjacentHTML('beforeend',`<div id="sihm-panel" class="sihm-overlay" hidden><section class="sihm-dialog"><header><h3>\u5a92\u4f53\u56fe\u5e8a\u7ba1\u5bb6</h3><button id="sihm-close" class="menu_button">\u5173\u95ed</button></header><p>\u4ec5\u626b\u63cf\u56fe\u7247\u548c MP3\uff0c\u81ea\u52a8\u5ffd\u7565 CSS\u3001JS \u548c\u7f51\u9875\u94fe\u63a5\u3002</p><div class="sihm-tabs"><select id="sihm-source" class="text_pole"><option value="character">\u89d2\u8272\u5361</option><option value="world">\u4e16\u754c\u4e66</option><option value="phone">\u5c0f\u624b\u673a</option><option value="beauty">\u7f8e\u5316</option></select><select id="sihm-filter" class="text_pole"><option value="issues">\u6709\u95ee\u9898</option><option value="ignored">\u5df2\u5ffd\u89c6\uff08\u8d85\u8fc7 20 \u5904\uff09</option></select></div><div class="sihm-controls"><input id="sihm-old-prefix" class="text_pole" placeholder="\u65e7\u56fe\u5e8a\u524d\u7f00"><span>\u2192</span><input id="sihm-new-prefix" class="text_pole" placeholder="\u65b0\u56fe\u5e8a\u524d\u7f00"><button id="sihm-prefix" class="menu_button">\u6279\u91cf\u8fc1\u79fb\u52fe\u9009\u4f4d\u7f6e</button></div><div id="sihm-count"></div><div id="sihm-results"></div></section></div>`);document.querySelector('#sihm-close').onclick=()=>document.querySelector('#sihm-panel').hidden=true;document.querySelector('#sihm-panel').onclick=e=>{if(e.target.id==='sihm-panel')e.target.hidden=true};document.querySelector('#sihm-source').onchange=scan;document.querySelector('#sihm-filter').onchange=render;document.querySelector('#sihm-prefix').onclick=prefixes;const b=document.createElement('div');b.id='sihm-open';b.className='list-group-item flex-container flexGap5 interactable';b.tabIndex=0;b.innerHTML='<i class="fa-solid fa-photo-film"></i><span>\u5a92\u4f53\u56fe\u5e8a\u7ba1\u5bb6</span>';b.onclick=openManager;(document.querySelector('#extensionsMenu')||document.body).append(b)}
function openManager(){document.querySelector('#sihm-panel').hidden=false;const mode=document.querySelector('#sihm-source')?.value||'character';scannedMode===mode?render():scan()}
function addSettingsEntry(){
 const host=document.querySelector('#extensions_settings2')||document.querySelector('#extensions_settings');
 if(!host||document.querySelector('#sihm-settings-entry'))return Boolean(host);
 host.insertAdjacentHTML('beforeend',`<div id="sihm-settings-entry" class="extension_container"><div class="inline-drawer"><div class="inline-drawer-toggle inline-drawer-header"><b><i class="fa-solid fa-images"></i> \u89d2\u8272\u5361\u56fe\u5e8a\u7ba1\u5bb6</b><div class="inline-drawer-icon fa-solid fa-circle-chevron-down down"></div></div><div class="inline-drawer-content"><p>\u626b\u63cf\u89d2\u8272\u5361\u6b63\u5219\u4e2d\u7684\u56fe\u7247\u94fe\u63a5\uff0c\u5b9a\u4f4d\u5931\u6548\u56fe\u5e8a\u5e76\u6279\u91cf\u66ff\u6362\u3002</p><button id="sihm-open-settings" class="menu_button"><i class="fa-solid fa-magnifying-glass"></i> \u6253\u5f00\u56fe\u5e8a\u7ba1\u5bb6</button></div></div></div>`);
 document.querySelector('#sihm-open-settings').onclick=openManager;return true;
}
$(function(){mount();if(!addSettingsEntry()){const observer=new MutationObserver(()=>{if(addSettingsEntry())observer.disconnect()});observer.observe(document.body,{childList:true,subtree:true});setTimeout(()=>observer.disconnect(),30000)}});

